# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sous}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nick Zadrozny"]
  s.date = %q{2010-02-01}
  s.default_executable = %q{sous}
  s.description = %q{Provision and prepare your chef-configured clusters.}
  s.email = %q{nick@beyondthepath.com}
  s.executables = ["sous"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/sous",
     "examples/aws.yml",
     "examples/cluster.rb",
     "lib/sous.rb",
     "lib/sous/cluster.rb",
     "lib/sous/environment.rb",
     "lib/sous/role.rb",
     "sous.gemspec",
     "spec/sous/cluster_spec.rb",
     "spec/sous/environment_spec.rb",
     "spec/sous/role_spec.rb",
     "spec/sous_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/beyondthepath/sous}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Provision and prepare your chef-configured clusters.}
  s.test_files = [
    "spec/sous/cluster_spec.rb",
     "spec/sous/environment_spec.rb",
     "spec/sous/role_spec.rb",
     "spec/sous_spec.rb",
     "spec/spec_helper.rb",
     "examples/cluster.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<fog>, [">= 0.0.40"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<fog>, [">= 0.0.40"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<fog>, [">= 0.0.40"])
  end
end

